import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://danwareacademy.netlify.app/">DanWare</a>
        </h1>

        <p className={styles.description}>Getting started with Recoil</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://danwareacademy.netlify.app/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by DanWare Academy
        </a>
      </footer>
    </div>
  );
}

export default Home
